### ISSUE TITLE
Publish to winget

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/vrc-get#19]
Depends on #15

**Comment by babo4d** [comment]
Hi. I added `vrc-get` to my [scoop bucket](https://github.com/babo4d/scoop-xrtools) (manifest [here](https://github.com/babo4d/scoop-xrtools/blob/master/bucket/vrc-get.json)). 

[Scoop](https://scoop.sh/) is more like homebrew for Windows, compared to chocolatey or winget, and it is more suitable for projects like this. 

Is it okay if I submit a PR to add it to your readme?

**Comment by anatawa12** [comment]
Yes, you can add to README!

Is it good idea to have logic to creatr pull request to your repository on release? 
Releasing new version of this project is semi-automatical.

**Comment by babo4d** [comment]
No need, it updates automatically with github actions :)

**Comment by anatawa12** [comment]
Close as completed since babo4d's scoop bucket is good enough.

Thank you a lot, babo4d.

**Comment by babo4d** [comment]
Hi, just letting you know that there is also a scoop manifest for ALCOM that can be installed like this:
```
scoop bucket add xrtools "https://github.com/babo4d/scoop-xrtools"
scoop install vrc-alcom
```
