### ISSUE TITLE
error loading unity project: invalid char: '^'

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/vrc-get#220]
cargo install vrc-get、x86_64-pc-windows-msvc-vrc-get.exeにてリポジトリを読みそうなコマンド（install, outdatedとか）が

```
error loading unity project: invalid char: '^'
```

なるエラーを吐き終了する

Windows 10 / Powershell 7

**Comment by anatawa12** [comment]
`vpm-manifest.json`にはバージョン range記法が許可されてないはずなのでそれが原因だと思います。

**Comment by Narazaka** [comment]
ぬ、たしか手動操作を一切していないvpm-manifestでさえ^が含まれているので許可されていないというのはなんかそういう仕様があるんですか？

**Comment by anatawa12** [comment]
手動操作してなくてもなるんですか...知らないうちに仕様変更されてますね...

対応入れておきます
