### ISSUE TITLE
publish to arch user repository 

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/vrc-get#236]
https://misskey.niri.la/notes/9km7ougw0c
https://misskey.niri.la/notes/9km7siew28

**Comment by anatawa12** [comment]
https://misskey.niri.la/notes/9km7jxrszd

**Comment by libjared** [comment]
I published vrc-get to AUR yesterday. I hope it was not premature or impolite to do so.
https://aur.archlinux.org/packages/vrc-get
I read that you want to automate publishing to AUR through GitHub Actions. Please feel free to use the above PKGBUILD as a template.

**Comment by anatawa12** [comment]
I'm interested in publishing to AUR through GitHub Actions but since I'm not a user of Arch Linux, It's hard to check the PKGBUILD is working well or not. So, If possible, I want someone to maintain AUR distribution of vrc-get.

**Comment by libjared** [comment]
I will be able to maintain the AUR.

I looked at GitHub Actions that publish a PKGBUILD to AUR, and they seem to
only handle the *publishing* step; they require a previous script to handle
generating the PKGBUILD with the correct version number, hashes, etc. So, I
haven't looked into automation further.

If you have any requests, suggestions, or would like me to add you or
someone else as an AUR maintainer, please feel free.

Thank you!

**Comment by anatawa12** [comment]
@libjared could you add @YTJVDCM as a maintainer of vrc-get on AUR?

**Comment by libjared** [comment]
Good idea, done.
