### ISSUE TITLE
error loading repositories: loading ....json: invalid char: 'v' at line 318 column 1

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/vrc-get#237]
`vrc-get.exe install foobar`を実行したら以下のエラーが発生しました。

```
error loading repositories: loading C:\Users\narazaka\AppData\Local\VRChatCreatorCompanion\Repos\04c4dc9f-d3a4-4aee-bf52-965d26e9e76e.json: invalid char: 'v' at line 318 column 1
```

当該のjsonファイルは https://vpm.rs64.net/vpm.json であり、その中に"v0.4.0-rc.2"等のsemverに厳密には従わないバージョン表記があります。
VCCはこの厳密ではないsemver指定のパッケージを正しくインストールすることが出来ますが、vrc-getはできません。

**Comment by anatawa12** [comment]
うーん... Semver.Netのバグとも言えそうな挙動ですね...

**Comment by anatawa12** [comment]
Semver.Netに意図的な挙動かきいて意図的と言われたら直します

**Comment by Narazaka** [comment]
Semver.NetのバグであったとしてVCCが修正バージョンにアップグレードするまでは非互換なのでちょっと不便かも……

**Comment by Narazaka** [comment]
ついでにローカルでjsonを直しても

```
> vrc-get.exe install idv.jlchntoz.vvmw
[2023-10-12T10:26:12Z ERROR vrc_get::vpm] fetching remote repo 'https://vpm.rs64.net/vpm.json': invalid char: 'v'
error loading unity project: invalid char: '^'
```

とリモートが駄目なら駄目っぽいです。

**Comment by anatawa12** [comment]
リモートのエラーは一応無視可能ですね(not fatail)更新ができなくなりますが

**Comment by anatawa12** [comment]
一応レポジトリ作者に連絡して修正はしてもらいました。(semver.netの現行の仕組みとしてv有り無しは無視されるので)

**Comment by Narazaka** [comment]
ぬ、Semver.Net的には意図的な挙動と言うことです？

**Comment by anatawa12** [comment]
v prefixはパース時及びスキップされるように実装はされてて、比較でも無視されてます。
でも意図的な仕様かは微妙なものだと思っています。
(npm semverから引きずったバグがいくつか過去にあってそれの修正pullreq通ってるので合わせることを著しく強く優先してる感じはない)

**Comment by anatawa12** [comment]
semver.netのほうが`v` prefixを読まなくなったのでcloseとします。vpmが独自にv prefixを許容するようにしてsemverを更新したらreopen https://github.com/adamreeve/semver.net/releases/tag/3.0.0-beta1
