### ISSUE TITLE
GUI

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/vrc-get#272]
vrc-get-gui / safeVCC

**Comment by anatawa12** [comment]
バックエンドはtauriかなぁってなってる。
フロントはreact?

**Comment by anatawa12** [comment]
litedb読むためにC#を多少やる必要がある。のでlitedbのラッパCLI作ってそれを呼ぶ?

**Comment by anatawa12** [comment]
先行 https://github.com/Gomorroth/vrc-get-gui/tree/main

**Comment by anatawa12** [comment]
あん
自動バックアップ

**Comment by anatawa12** [comment]
changelog出したい

**Comment by Sayamame-beans** [comment]
ConsoleLogSaverの組み込み
(Viewerもついでに組み込む?)

**Comment by Sayamame-beans** [comment]
コミュニティお勧めのテンプレートを生やす? (lilToon等を入れておく感じの)

**Comment by anatawa12** [comment]
散らかるので https://github.com/users/anatawa12/projects/2 に変えて、それぞれ別issueにします。
