### ISSUE TITLE
なんか並列になってなさそう

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/vrc-get#275]
https://github.com/anatawa12/vrc-get/blob/d91243a3429ca74c74fa92500e0ca132ce9dd41f/vrc-get-vpm/src/lib.rs#L1902-L1931

**Comment by bdunderscore** [comment]
https://docs.rs/futures/latest/futures/macro.join.html
https://docs.rs/futures/latest/futures/future/fn.join_all.html
