### ISSUE TITLE
インストールされたパッケージとバージョンをコンソールで表示

### ISSUE THREAD

**Issue by bdunderscore** [anatawa12/vrc-get#276]
CIを回してる場合などは、どのバージョンをインストールしたのログがあると助かります。

もしかしたらenv-varによる設定がどこかにあるかもしれませんが、`--help`に乗ってないし、CLIツールなので`-v`などのフラグがあると分かりやすいかと思います。

**Comment by anatawa12** [comment]
#273 で一緒に実装してある情報で十分でしょうか

**Comment by bdunderscore** [comment]
十分っぽいけどPR見ただけでは表示される条件がわからないですね・・・

**Comment by anatawa12** [comment]
表示は常に行われるようにしてます

**Comment by anatawa12** [comment]
actionの方でインストール済パッケージ一覧表示するコマンドを叩くようにしたのでこれで対応完了とします。

anatawa12/sh-actions#12
