### ISSUE TITLE
Project Management

### ISSUE THREAD

**Issue by anatawa12** [anatawa12/vrc-get#292]
プロジェクトのリストを読む機能。

litedb読むためにC#を多少やる必要がある。のでlitedbのラッパCLI作ってそれを呼ぶ?

**Comment by anatawa12** [comment]
litedbメモ

https://misskey.niri.la/notes/9o853je56k

**Comment by Sayamame-beans** [comment]
> 欲を言うと: 各プロジェクトごとにメモ欄orタグ付け機能あると良さそう
> 名前だけだと管理キツい
https://misskey.niri.la/notes/9pgvbnwzvw

**Comment by anatawa12** [comment]
とりあえずミニマムで来たのでclose
