### ISSUE TITLE
想定のパスにプロジェクトが見当たらない場合に一覧から削除しない

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/vrc-get#368]
> VCCって対象プロジェクトのパスにフォルダ見当たらなかったら一覧から削除するけど、求められているのはmissing(このプロジェクトどこか行った?消した?)のままにすることかも
https://misskey.niri.la/notes/9pgv7weuo6

本家にも書いた方が良さそうではある(未定)

**Comment by Sayamame-beans** [comment]
related: #292

**Comment by anatawa12** [comment]
作ったproject managementは消さない設計にしたのでDone
