### ISSUE TITLE
GUIからUnityを立ち上げると、Task Manager上Unityがvrc-getの一部として扱われる

### ISSUE THREAD

**Issue by bdunderscore** [anatawa12/vrc-get#456]
![image](https://github.com/anatawa12/vrc-get/assets/64174065/677343e1-15ba-47ab-aaa6-76b56d70731a)

**Comment by anatawa12** [comment]
プロセスを分割する方法がわからなかったんですよね...
Win32 APIレベルでもいいので方法がわかれば実装したい感じです

**Comment by anatawa12** [comment]
https://github.com/rust-lang/rust/blob/1.76.0/library/std/src/sys/windows/process.rs#L294 と同じ実装をしても動かなかったため、対応方法が不明になっています

**Comment by anatawa12** [comment]
うーんネット上で調べても`cmd /c start "Unity" "/path/to/exe"`以外でないからそれで実装するしかないかなぁあ
