### ISSUE TITLE
Build failure (missing submodule?)

### ISSUE THREAD

**Issue by i0ntempest** [anatawa12/vrc-get#464]
I'm trying to publish this to MacPorts but I'm getting a build failure:
```
:info:build      Running `/opt/local/var/macports/build/_Users_Admin_Developer_Ports_devel_vrc-get/vrc-get/work/vrc-get-d9436fdc522a9f76a7923ea6cd2f80248a03e33f/target/release/build/vrc-get-litedb-dff723900186e0d5/build-script-build`
:info:build error: failed to run custom build command for `vrc-get-litedb v0.1.4-beta.0 (/opt/local/var/macports/build/_Users_Admin_Developer_Ports_devel_vrc-get/vrc-get/work/vrc-get-d9436fdc522a9f76a7923ea6cd2f80248a03e33f/vrc-get-litedb)`
:info:build Caused by:
:info:build   process didn't exit successfully: `/opt/local/var/macports/build/_Users_Admin_Developer_Ports_devel_vrc-get/vrc-get/work/vrc-get-d9436fdc522a9f76a7923ea6cd2f80248a03e33f/target/release/build/vrc-get-litedb-dff723900186e0d5/build-script-build` (exit status: 101)
:info:build   --- stdout
:info:build   cargo:rerun-if-changed=build.rs
:info:build   cargo:rerun-if-changed=dotnet/vrc-get-litedb.csproj
:info:build   cargo:rerun-if-changed=dotnet/src
:info:build   cargo:rerun-if-changed=dotnet/LiteDB/LiteDB
:info:build   --- stderr
:info:build   thread 'main' panicked at vrc-get-litedb/build.rs:116:35:
:info:build   called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }
:info:build   stack backtrace:
:info:build      0: _rust_begin_unwind
:info:build      1: core::panicking::panic_fmt
:info:build      2: core::result::unwrap_failed
:info:build      3: core::result::Result<T,E>::unwrap
:info:build                at /opt/local/libexec/rust/src/rustc-1.75.0-src/library/core/src/result.rs:1077:23
:info:build      4: build_script_build::build_dotnet
:info:build                at ./build.rs:116:18
:info:build      5: build_script_build::main
:info:build                at ./build.rs:21:29
:info:build      6: core::ops::function::FnOnce::call_once
:info:build                at /opt/local/libexec/rust/src/rustc-1.75.0-src/library/core/src/ops/function.rs:250:5
:info:build   note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
:info:build warning: build failed, waiting for other jobs to finish...
:info:build Command failed:  cd "/opt/local/var/macports/build/_Users_Admin_Developer_Ports_devel_vrc-get/vrc-get/work/vrc-get-d9436fdc522a9f76a7923ea6cd2f80248a03e33f" && /opt/local/bin/cargo build --release --frozen -v -j24 
:info:build Exit code: 101
```
I'm not familiar with rust so I'm hoping I can get some help here. I thought maybe it's caused by missing submodules but running `git submodule update` does not resolve the issue. Full log attached below.
[main.log](https://github.com/anatawa12/vrc-get/files/14443465/main.log)

**Comment by anatawa12** [comment]
To initialize submodule, we have to call `git submodule update --init` instead of `git submodule update`.

Since vrc-get-litedb crate is rarely updated, the `vrc-get` (`vrc-get-vpm`) crate uses `vrc-get-litedb` from crates.io so it's not nessesary to build `vrc-get-litedb` crate on the repository for building `vrc-get`.
I think it's better to skip building `vrc-get-litedb` (and other unnecessary crates in this repository) by calling `cargo build -p vrc-get`.

**Comment by i0ntempest** [comment]
Sorry for the confision - I did actually run `git submodule update --init`. Passing `-p vrc-get` does work, but building `vrc-get-gui` will automatically build `vrc-get-litedb` and will end up in the same error above.

**Comment by anatawa12** [comment]
The `vrc-get-gui` already depends on `vrc-get-litedb` and `vrc-get-litedb` currently depends on `dotnet` on build time for technical reasons.
Since upstream litedb is written in C#, I have to decide to rewrite in Rust or use C# with NativeAOT and I chose NativeAOT for now.
However, NativeAOT has many punch holes so I'm planned to rewrite litedb in rust (#376) but it's not yet started.

the `vrc-get` command does not depends on `vrc-get-litedb`, unless we enabled `experimental-vcc` feature, which includes features for package and unity management.

I'm not forward to add vrc-get-gui to some package manager because vrc-get-gui is still in early development and not have icon and final name (see #453).

**Comment by anatawa12** [comment]
Thank you for submitting vrc-get to MacPorts.
I'll add to README later.

**Comment by anatawa12** [comment]
@i0ntempest Thank you for work on macports maintaince. I'm here to let you know ALCOM (at the time it was called vrc-get-gui) has been released as v1 and ready for package manager.

**Comment by i0ntempest** [comment]
> [<img alt="" width="16" height="16" src="https://avatars.githubusercontent.com/u/16017904?s=64&amp;u=6d639b84a7f4975fdbd14ca3e2b2fc999ed29cbe&amp;v=4">@i0ntempest](https://github.com/i0ntempest) Thank you for work on macports maintaince. I'm here to let you know ALCOM (at the time it was called vrc-get-gui) has been released as v1 and ready for package manager.

Glad to know! But can we build everything without using .NET now? If not it's still very complicated to build ALCOM using MacPorts (also the `experimental-vcc` feature in vrc-get).

**Comment by anatawa12** [comment]
> But can we build everything without using .NET now?

No yet. sorry.

We have binary build archived to tar.gz on releases so it might be possible to just download prebuilt binary from github. (if macports allows), or just leave missing from macports is OK to me.

**Comment by i0ntempest** [comment]
> > But can we build everything without using .NET now?
> 
> No yet. sorry.
> 
> We have binary build archived to tar.gz on releases so it might be possible to just download prebuilt binary from github. (if macports allows), or just leave missing from macports is OK to me.

MP generally does not want pure binary redistribution if building from source is possible. I'll wait for litedb problems to be sorted out.
