### ISSUE TITLE
インストールでエラーが起きる場合、エラー文が見えない、コピペできない

### ISSUE THREAD

**Issue by bdunderscore** [anatawa12/vrc-get#467]
![image](https://github.com/anatawa12/vrc-get/assets/64174065/0b6605f4-9983-4831-b535-da0bdce17f0d)
こうやってエラー文が途切れて見れないし、時間制限があるためコピペもできなさそう
beta.3で確認しました。

**Comment by anatawa12** [comment]
コピーできない問題は #468 でどうにかします。
