### ISSUE TITLE
vrc-get upgradeでlockedの空のdependenciesキーが削除される？

### ISSUE THREAD

**Issue by Narazaka** [anatawa12/vrc-get#473]
### Description of the bug / バグの説明

VCCでAAO 1.6.6->1.6.7にアップグレードした差分
![image](https://github.com/anatawa12/vrc-get/assets/1712548/2c119366-cd52-4486-8fb9-897b6c6ff6f0)
vrc-getでAAO 1.6.6->1.6.7にアップグレードした差分
![image](https://github.com/anatawa12/vrc-get/assets/1712548/b824d747-9661-44e9-bd38-b3225f1e2606)

順序差についてはjson同義なので良いと思うが、dependenciesキーがなくなる点についてはjson同義でないため気になった

あとこのissueとは別だがVCCがdependenciesキー内もアプデするようになったっぽいのか……？

### Steps to Reproduce / 再現手順

```
PS D:\make\devel\vrchat-avatar-template-2022-vrm> vrc-get upgrade com.anatawa12.avatar-optimizer
[2024-02-29T16:52:10Z ERROR vrc_get_vpm::environment::repo_holder] fetching remote repo 'https://www.dreadrith.com/': expected value at line 1 column 1
You're installing the following packages:
- com.anatawa12.avatar-optimizer version 1.6.7
upgraded com.anatawa12.avatar-optimizer to 1.6.7
PS D:\make\devel\vrchat-avatar-template-2022-vrm>
```

### Expected Behavior / 想定される挙動

json同義であるのが望ましい

### Software Version / バージョン情報

1.7.0

### OS

Windows 10 Pro 22H2

**Comment by anatawa12** [comment]
vrc-get実装当初はVpm側が追加しなかったので変わったやつですね...

順番は多分 https://github.com/vrchat-community/creator-companion/issues/406 ですね
