### ISSUE TITLE
vrc-get repo packages description might be wrong in program

### ISSUE THREAD

**Issue by Sayamame-beans** [anatawa12/vrc-get#49]
https://github.com/anatawa12/vrc-get/blob/e21699a5d6628e4209ba3fc3bfb9c201c7d10791/src/commands.rs#L593-L602

**Comment by anatawa12** [comment]
That's incorrect. Can you fix this?

**Comment by Sayamame-beans** [comment]
Ah… Does your "doc" mean command description? Or README.md?
If "doc" is command description, the answer is YES.
If not, please tell me the true behavior of RepoPackages.

**Comment by anatawa12** [comment]
I mean doc comment, same as command description in --help command.

**Comment by Sayamame-beans** [comment]
OK. (maybe it was lack of my knowledge)
I'll do that.
