### ISSUE TITLE
d4rkAvatarOptimizer is "Not Installed" in the project even when it is installed

### ISSUE THREAD

**Issue by hai-vr** [anatawa12/vrc-get#491]
### Description of the bug / バグの説明

Package d4rkpl4y3r.d4rkavataroptimizer is marked as "Not Installed" in the project, even if it is installed in the project.

### Steps to Reproduce / 再現手順

- Add the listing described in https://github.com/d4rkc0d3r/d4rkAvatarOptimizer to the repositories
- Add d4rkAvatarOptimizer to an Avatars project (either using Creator Companion or vrc-get-gui)

Observed:
- d4rkAvatarOptimizer is marked as "Not Installed" in vrc-get-gui

### Expected Behavior / 想定される挙動

d4rkAvatarOptimizer should be marked as "3.5.2" in vrc-get-gui

### Screenshots / スクリーンショット

![image](https://github.com/anatawa12/vrc-get/assets/60819407/daa628d4-45d4-4030-a46b-967f46a78598)

### Software Version / バージョン情報

0.1.0-beta.3-x86_64.exe

### OS

Windows 10 Pro 22H2 + Sandboxie-Plus v1.11.0e

**Comment by anatawa12** [comment]
Thank you for bug report!

It looks `url` field in `Packages/d4rkpl4y3r.d4rkavataroptimizer/package.json` is empty string, which is invalid for url, and vrc-get expects some valid url or just omit `url` in `Packages` folder so vrc-get fails to load package.json from. I'll make the restrictions for url field relaxed.
